gword = [{text: 'Iraq', size: 100},
{text: 'Pakistan', size: 73},
{text: 'Afghanistan', size: 68},
{text: 'India', size: 40},
{text: 'Nigeria', size: 34},
{text: 'Yemen', size: 33},
{text: 'Philippines', size: 33},
{text: 'Ukraine', size: 28},
{text: 'Somalia', size: 28},
{text: 'Thailand', size: 27},
{text: 'Libya', size: 27},
{text: 'Egypt', size: 26},
{text: 'Syria', size: 26},
{text: 'Bangladesh', size: 22},
{text: 'Turkey', size: 22},
{text: 'Colombia', size: 21},
{text: 'West Bank and Gaza Strip', size: 20},
{text: 'Israel', size: 20},
{text: 'Sudan', size: 20},
{text: 'United Kingdom', size: 20}
];
