gword = [{text: 'Iraq', size: 100},
{text: 'Pakistan', size: 74},
{text: 'Afghanistan', size: 69},
{text: 'India', size: 42},
{text: 'Nigeria', size: 36},
{text: 'Yemen', size: 36},
{text: 'Philippines', size: 36},
{text: 'Ukraine', size: 31},
{text: 'Somalia', size: 31},
{text: 'Thailand', size: 30},
{text: 'Libya', size: 29},
{text: 'Egypt', size: 29},
{text: 'Syria', size: 29},
{text: 'Bangladesh', size: 25},
{text: 'Turkey', size: 25},
{text: 'Colombia', size: 24},
{text: 'West Bank and Gaza Strip', size: 23},
{text: 'Israel', size: 23},
{text: 'Sudan', size: 22},
{text: 'United Kingdom', size: 22},
{text: 'Lebanon', size: 22},
{text: 'Russia', size: 22},
{text: 'Kenya', size: 22},
{text: 'Democratic Republic of the Congo', size: 22},
{text: 'Mali', size: 21},
{text: 'Nepal', size: 21},
{text: 'Central African Republic', size: 21},
{text: 'Cameroon', size: 21},
{text: 'Bahrain', size: 20},
{text: 'Indonesia', size: 20},
{text: 'Greece', size: 20},
{text: 'Saudi Arabia', size: 20},
{text: 'France', size: 20},
{text: 'South Sudan', size: 20},
{text: 'Ireland', size: 20},
{text: 'United States', size: 20},
{text: 'Algeria', size: 20},
{text: 'Burundi', size: 20},
{text: 'Myanmar', size: 20},
{text: 'Germany', size: 20},
{text: 'Tunisia', size: 20},
{text: 'China', size: 20},
{text: 'Mozambique', size: 20},
{text: 'Niger', size: 20},
{text: 'Paraguay', size: 20},
{text: 'Mexico', size: 20},
{text: 'Sri Lanka', size: 20},
{text: 'Sweden', size: 20},
{text: 'South Africa', size: 20},
{text: 'Peru', size: 20},
{text: 'Iran', size: 20},
{text: 'Malaysia', size: 20},
{text: 'Tanzania', size: 20},
{text: 'Chad', size: 20},
{text: 'Italy', size: 20},
{text: 'Ivory Coast', size: 20},
{text: 'Chile', size: 20},
{text: 'Uganda', size: 20},
{text: 'Senegal', size: 20},
{text: 'Cyprus', size: 20},
{text: 'Ethiopia', size: 20},
{text: 'Kosovo', size: 20},
{text: 'Japan', size: 20},
{text: 'Maldives', size: 20},
{text: 'Australia', size: 20},
{text: 'Canada', size: 20},
{text: 'Rwanda', size: 20},
{text: 'Bosnia-Herzegovina', size: 20},
{text: 'Brazil', size: 20},
{text: 'Czech Republic', size: 20},
{text: 'Jordan', size: 20},
{text: 'Tajikistan', size: 20},
{text: 'Kazakhstan', size: 20},
{text: 'Macedonia', size: 20},
{text: 'Spain', size: 20},
{text: 'Venezuela', size: 20},
{text: 'Bulgaria', size: 20},
{text: 'Finland', size: 20},
{text: 'Albania', size: 20},
{text: 'Georgia', size: 20},
{text: 'Guatemala', size: 20},
{text: 'Burkina Faso', size: 20},
{text: 'Argentina', size: 20},
{text: 'Denmark', size: 20},
{text: 'Kyrgyzstan', size: 20},
{text: 'Madagascar', size: 20},
{text: 'Trinidad and Tobago', size: 20},
{text: 'Zimbabwe', size: 20},
{text: 'Ecuador', size: 20},
{text: 'Serbia', size: 20},
{text: 'Laos', size: 20},
{text: 'Armenia', size: 20},
{text: 'Netherlands', size: 20},
{text: 'Azerbaijan', size: 20},
{text: 'Belgium', size: 20},
{text: 'United Arab Emirates', size: 20},
{text: 'Belarus', size: 20},
{text: 'Guinea', size: 20},
{text: 'Montenegro', size: 20},
{text: 'Liberia', size: 20}
];
